### ISSUE TITLE
URL examples seem to be incorrect

### ISSUE THREAD

**Issue by Sovietaced** [awslabs/aws-postgresql-jdbc#61]
Please read https://stackoverflow.com/help/minimal-reproducible-example 

**Describe the issue**
I just tried to get this PostgreSQL driver working and hit some speedbumps that required digging into the source code. I'm not sure if this is an artifact of Hikari or not but it appears that [the driver requires a trailing slash](https://github.com/awslabs/aws-postgresql-jdbc/blob/84570ce5f0f20e9d10dcc360b6c5648ee2e13d48/pgjdbc/src/main/java/software/aws/rds/jdbc/postgresql/Driver.java#L533-L538) on the JDBC url. 

```Driver software.aws.rds.jdbc.postgresql.Driver claims to not accept jdbcUrl, jdbc:postgresql:aws://localhost:46083```

**Driver Version?** 
0.1.0

**To Reproduce**
```java
  private final HikariConfig config = new HikariConfig();
  config.setJdbcUrl("jdbc:postgresql:aws://" + host + ":" + port);
  //...
  // Eventually get a connection
  
```

**Expected behaviour**
I would expect the URL to work, however the warning message was helpful. 

**Logs**
```
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - The files belonging to this database system will be owned by user "jparraga".
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - This user must also own the server process.
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - 
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - The database cluster will be initialized with locale "en_US.UTF-8".
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - The default text search configuration will be set to "english".
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - 
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - Data page checksums are disabled.
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - 
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - fixing permissions on existing directory /tmp/epg11000978009499568094 ... ok
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - creating subdirectories ... ok
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - selecting default max_connections ... 100
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - selecting default shared_buffers ... 128MB
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - selecting dynamic shared memory implementation ... posix
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - creating configuration files ... ok
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - running bootstrap script ... ok
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - performing post-bootstrap initialization ... ok
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - syncing data to disk ... ok
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - 
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - Success. You can now start the database server using:
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - 
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb -     /tmp/embedded-pg/PG-12c02d3f154185f003cc5445837a4be4/bin/pg_ctl -D /tmp/epg11000978009499568094 -l logfile start
[log:pid(78217)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:initdb - 
[Test worker] INFO com.opentable.db.postgres.embedded.EmbeddedPostgres - 03d520c9-2edc-4664-a645-e5131d42e636 initdb completed in 00:00:00.748
[Test worker] INFO com.opentable.db.postgres.embedded.EmbeddedPostgres - 03d520c9-2edc-4664-a645-e5131d42e636 postmaster started as Process[pid=78240, exitValue="not exited"] on port 46083.  Waiting up to PT10S for server startup to finish.
[log:pid(78240)] INFO pg-03d520c9-2edc-4664-a645-e5131d42e636 - waiting for server to start....2022-01-04 14:34:19.568 PST [78244] LOG:  listening on IPv6 address "::1", port 46083
[log:pid(78240)] INFO pg-03d520c9-2edc-4664-a645-e5131d42e636 - 2022-01-04 14:34:19.569 PST [78244] LOG:  listening on IPv4 address "127.0.0.1", port 46083
[log:pid(78240)] INFO pg-03d520c9-2edc-4664-a645-e5131d42e636 - 2022-01-04 14:34:19.569 PST [78244] LOG:  listening on Unix socket "/tmp/.s.PGSQL.46083"
[log:pid(78240)] INFO pg-03d520c9-2edc-4664-a645-e5131d42e636 - 2022-01-04 14:34:19.581 PST [78245] LOG:  database system was shut down at 2022-01-04 14:34:19 PST
[log:pid(78240)] INFO pg-03d520c9-2edc-4664-a645-e5131d42e636 - 2022-01-04 14:34:19.582 PST [78244] LOG:  database system is ready to accept connections
[log:pid(78240)] INFO pg-03d520c9-2edc-4664-a645-e5131d42e636 - 2022-01-04 14:34:19.655 PST [78257] LOG:  incomplete startup packet
[Test worker] INFO com.opentable.db.postgres.embedded.EmbeddedPostgres - 03d520c9-2edc-4664-a645-e5131d42e636 postmaster startup finished in 00:00:00.108
[log:pid(78240)] INFO pg-03d520c9-2edc-4664-a645-e5131d42e636 -  done
[log:pid(78240)] INFO pg-03d520c9-2edc-4664-a645-e5131d42e636 - server started
[Test worker] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Starting...
Jan 04, 2022 2:34:19 PM software.aws.rds.jdbc.postgresql.Driver parseURL
WARNING: JDBC URL must contain a / at the end of the host or port: jdbc:postgresql:aws://localhost:46083
[log:pid(78240)] INFO pg-03d520c9-2edc-4664-a645-e5131d42e636 - 2022-01-04 14:34:19.693 PST [78244] LOG:  received fast shutdown request
[log:pid(78259)] INFO init-03d520c9-2edc-4664-a645-e5131d42e636:pg_ctl - waiting for server to shut down.... done
[Test worker] INFO com.opentable.db.postgres.embedded.EmbeddedPostgres - 03d520c9-2edc-4664-a645-e5131d42e636 shut down postmaster in 00:00:00.104

Driver software.aws.rds.jdbc.postgresql.Driver claims to not accept jdbcUrl, jdbc:postgresql:aws://localhost:46083
```

Looking at the exception message at the bottom is quite confusing when I am using a URL that matches the examples in the README.

**Comment by Sovietaced** [comment]
I tried reproducing the issue using the driver only and I was unable to, however now it seems to produce strange authentication issues. 

```java
  @Test
  public void test() throws Exception {
    final String url = "jdbc:postgresql:aws://" + postgres.getContainerIpAddress() + ":" + postgres.getFirstMappedPort();
    final Properties props = new Properties();
    props.setProperty("user", postgres.getUsername());
    props.setProperty("password", postgres.getPassword());
    try ( Connection conn = DriverManager.getConnection(url, props) ){
      try ( Statement statement = conn.createStatement() ) {
        try (ResultSet rs = statement.executeQuery( "SELECT 1") ){
          if (rs.next())
            System.out.println( "Get String: " + rs.getString(1));
        }
      }
    }
  }
```  

```
Jan 04, 2022 7:08:15 PM software.aws.rds.jdbc.postgresql.Driver parseURL
WARNING: JDBC URL must contain a / at the end of the host or port: jdbc:postgresql:aws://localhost:49255

FATAL: password authentication failed for user "test"
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "test"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:520)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
```
